# -*- coding: utf-8 -*-
"""3D_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jd5obweNf-DVXf5U42S5srDpCJECYDvw
"""

!pip install torch torchvision
!pip install torch_geometric

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch_geometric.transforms as T
from torch_geometric.datasets import ModelNet
from torch_geometric.loader import DataLoader

# ==========================================
# 1. Model Architecture (PointNet)
# ==========================================

class TNet(nn.Module):
    """
    Transformation Network: Learns a transformation matrix to align
    the input point cloud to a canonical, rotation-invariant space.
    """
    def __init__(self, k=3):
        super(TNet, self).__init__()
        self.k = k
        self.conv1 = nn.Conv1d(k, 64, 1)
        self.conv2 = nn.Conv1d(64, 128, 1)
        self.conv3 = nn.Conv1d(128, 1024, 1)

        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, k * k)

        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(1024)
        self.bn4 = nn.BatchNorm1d(512)
        self.bn5 = nn.BatchNorm1d(256)

    def forward(self, x):
        batch_size = x.size(0)

        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))

        x = nn.MaxPool1d(x.size(-1))(x)
        x = nn.Flatten(1)(x)

        x = F.relu(self.bn4(self.fc1(x)))
        x = F.relu(self.bn5(self.fc2(x)))

        # Initialize identity matrix
        init = torch.eye(self.k, requires_grad=True).repeat(batch_size, 1, 1).to(x.device)
        matrix = self.fc3(x).view(-1, self.k, self.k) + init
        return matrix


class PointNetClassifier(nn.Module):
    """
    Main PointNet architecture for 3D classification.
    """
    def __init__(self, num_classes=40):
        super(PointNetClassifier, self).__init__()
        self.tnet = TNet(k=3)

        self.conv1 = nn.Conv1d(3, 64, 1)
        self.conv2 = nn.Conv1d(64, 128, 1)
        self.conv3 = nn.Conv1d(128, 1024, 1)

        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(1024)

        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, num_classes)

        self.bn4 = nn.BatchNorm1d(512)
        self.bn5 = nn.BatchNorm1d(256)
        self.dropout = nn.Dropout(p=0.3)

    def forward(self, x):
        # 1. Transform input points
        trans_matrix = self.tnet(x)
        x = x.transpose(1, 2)
        x = torch.bmm(x, trans_matrix)
        x = x.transpose(1, 2)

        # 2. Feature Extraction
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))

        # 3. Global Max Pooling (Permutation Invariance)
        x = nn.MaxPool1d(x.size(-1))(x)
        x = nn.Flatten(1)(x)

        # 4. Classification Head
        x = F.relu(self.bn4(self.fc1(x)))
        x = F.relu(self.bn5(self.dropout(self.fc2(x))))
        output = self.fc3(x)

        return output

# ==========================================
# 2. Data Loading & Augmentation
# ==========================================
def get_dataloaders(batch_size=32, num_points=1024):
    print("Downloading/Loading ModelNet40 Dataset...")

    # Augmentations: Sample exactly 1024 points from the 3D meshes and normalize scale
    train_transforms = T.Compose([
        T.SamplePoints(num_points),
        T.NormalizeScale() # Fits the point cloud into a unit sphere (crucial for PointNet)
    ])

    test_transforms = T.Compose([
        T.SamplePoints(num_points),
        T.NormalizeScale()
    ])

    train_dataset = ModelNet(root='data/ModelNet40', name='40', train=True, transform=train_transforms)
    test_dataset = ModelNet(root='data/ModelNet40', name='40', train=False, transform=test_transforms)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, test_loader, num_points

# ==========================================
# 3. Training and Evaluation Loop
# ==========================================
def main():
    # Hyperparameters
    BATCH_SIZE = 32
    NUM_POINTS = 1024
    EPOCHS = 15
    LEARNING_RATE = 0.001

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Load Data
    train_loader, test_loader, num_points = get_dataloaders(BATCH_SIZE, NUM_POINTS)

    # Initialize Model, Loss, and Optimizer
    model = PointNetClassifier(num_classes=40).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    print("\nStarting Training...")
    for epoch in range(EPOCHS):
        # --- TRAINING PHASE ---
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for data in train_loader:
            # PyG batches points in a 2D array. We need to reshape to (Batch, 3, Num_Points)
            points = data.pos.view(-1, num_points, 3).transpose(1, 2).to(device)
            labels = data.y.to(device)

            optimizer.zero_grad()

            outputs = model(points)
            loss = criterion(outputs, labels)

            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()

        train_acc = 100 * train_correct / train_total

        # --- EVALUATION PHASE ---
        model.eval()
        test_correct = 0
        test_total = 0

        with torch.no_grad():
            for data in test_loader:
                points = data.pos.view(-1, num_points, 3).transpose(1, 2).to(device)
                labels = data.y.to(device)

                outputs = model(points)
                _, predicted = torch.max(outputs.data, 1)

                test_total += labels.size(0)
                test_correct += (predicted == labels).sum().item()

        test_acc = 100 * test_correct / test_total

        # Print Results
        print(f"Epoch [{epoch+1:02d}/{EPOCHS}] "
              f"| Train Loss: {train_loss/len(train_loader):.4f} "
              f"| Train Acc: {train_acc:.2f}% "
              f"| Test Acc: {test_acc:.2f}%")

if __name__ == '__main__':
    main()